version: "3.8"

services:
  postgis:
    image: postgis/postgis
    container_name: postgis-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
